/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorLogsRouteImport } from './routes/error-logs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorLogsRoute = ErrorLogsRouteImport.update({
  id: '/error-logs',
  path: '/error-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/error-logs': typeof ErrorLogsRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/error-logs': typeof ErrorLogsRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/error-logs': typeof ErrorLogsRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/audit-logs'
    | '/dashboard'
    | '/error-logs'
    | '/login'
    | '/not-found'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/audit-logs'
    | '/dashboard'
    | '/error-logs'
    | '/login'
    | '/not-found'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/audit-logs'
    | '/dashboard'
    | '/error-logs'
    | '/login'
    | '/not-found'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AuditLogsRoute: typeof AuditLogsRoute
  DashboardRoute: typeof DashboardRoute
  ErrorLogsRoute: typeof ErrorLogsRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-logs': {
      id: '/error-logs'
      path: '/error-logs'
      fullPath: '/error-logs'
      preLoaderRoute: typeof ErrorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AuditLogsRoute: AuditLogsRoute,
  DashboardRoute: DashboardRoute,
  ErrorLogsRoute: ErrorLogsRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
